sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ptBshBF9qn+oWAVQqXk6hp9pXM02g9rXZuxmSJ5o8EDwt0YuyufQ4XVPjgHwxp84ckVDN5TuC8w42YhZdUpkz1FiQ4SJHCYKQIaFybwfBr42K3ni0L4g36ru5a2mffaqtohDY/Sv8Sp4xHZdhDG5xE75yzd9nPKDtfCgTk4rM+ypMbYRzB4FtS7VhYIwh/B6WFGZPaL6JaJCJTp7he1qA+EF5qhVwwDwHuUcMK1NlFqOl5em1Np1EInCKEGsHKshtVrjfAYSd5YuYimSeeivm6L+pYCxJvqwdPaDcKKVmqqoI4C0QQC8m6KunppYRwTbNiNu22W5dTE2xgxObWUMNvPDzWQeG4VBH/mJASjsBAFFvS9+23Lmn+rE5ca0VmV1I0iDcqHjSrnGUmmdwpJQewz/NQU7q8HYETU85+6yncZo9P7HLUEvKDjb2UNqoayLdLlAdv+nqmjBAelZE2TXR3w56Fz9r8z5jgp9RAHB8lnN36HSdd/7s7roeQTHgc/yZVK0ALQASjzbTa+h2jj66WM+OeCL1MMZR3FZyVrDUmG2WtGUpJSox1YiaxhA1ZfuAGWhj6z4Q8BkeKPOuWJ2XfU85YRtYswDjPJ4++PNNbyd0uCqV6lFvs7AQjMUdRLp0I+ea85rz0v70C7BTTJliTKL1PPsqJPdT/R/XuDYK4k=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Island-Pharisees_2771
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy